default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: protospace_40243_development

  <<: *default
  database: protospace_40243_test

production:
  <<: *default
  database: protospace_40243_production
  username: protospace_40243
  password: <%= ENV["PROTOSPACE_40243_DATABASE_PASSWORD"] %>
